---
- name: Create a db server instance
  os_server:
    cloud: ospcloud
    name: db
    image: rhel-guest
    meta: group=db,deployment_name=QA
    flavor: m1.medium
    security_groups: db
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: int_network
    userdata: |
      #!/bin/bash
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo.
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  register: instanceip


- name: Add floating IP to db
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: db
    network: ext_network
    wait: true
    timeout: 180
  register: instancefloatingip

- name: Show "{{ instanceip }}" public IP
  debug: var=instancefloatingip.floating_ip.floating_ip_address

- name: Wait for db to be available
  wait_for:
    host: "{{ instancefloatingip.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  delegate_to: "{{ inventory_hostname }}"
